  const wmc = "https://upload.wikimedia.org/wikipedia/commons";
  const o365 = "https://raw.githubusercontent.com/sempostma/office365-icons/refs/heads/master/svg";
  const data = { 
  "AI": [
    { "name": "Gemini", "url": "https://gemini.google.com"},
    { "name": "Copilot", "url": "https://copilot.microsoft.com"},
    { "name": "Meta", "url": "https://www.meta.ai/"},
    { "name": "Deepseek", "url": "https://chat.deepseek.com"},
    { "name": "ChatGPT", "url": "https://chatgpt.com"},
    { "name": "Perplexity", "url": "https://www.perplexity.ai", "background": "#111"},
    { "name": "Claude", "url": "https://claude.ai"},
    { "name": "Grok", "url": "https://grok.com"},
    { "name": "HIX", "url": "https://hix.ai/"},
    { "name": "DeepAI", "url": "https://deepai.org/"},
    "break",
    { "name": "FireFlies", "url": "https://app.fireflies.ai/"},
    { "name": "PixVerse", "url": "https://app.pixverse.ai/"},
    { "name": "Suno", "url": "https://suno.com/home"},
  ],
  "Browse" : [
    { "name": "Google", "url": "https://www.google.pt", "icon": "https://www.google.pt/images/branding/googleg/1x/googleg_standard_color_128dp.png"},
    { "name": "DuckDuckGo ", "url": "https://duckduckgo.com/", "icon": "https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/duckduckgo-icon.svg" },
    { "name": "Bing", "url": "https://www.bing.com/", "icon": `${wmc}/f/f3/Bing_Logo.svg` },
    { "name": "Dogpile", "url": "https://www.dogpile.com/", "icon": "https://www.dogpile.com/static/info.dogpile.com/favicon-32x32.png" }
    ],
  "Social" : [
    {"name": "Whatsapp", "url": "https://web.whatsapp.com/"},
    {"name": "LinkedIn", "url": "https://www.linkedin.com/", "background": "#0073b2"},
    {"name": "Threads", "url": "https://www.threads.net", "background": "#000"},
    {"name": "Instagram", "url": "https://www.instagram.com"},
    {"name": "BlueSky", "url": "https://bsky.app"},
    {"name": "Reddit", "url": "https://www.reddit.com/", "b2": "#ff4500"},
    {"name": "Pinterest", "url": "https://www.pinterest.com/", "b2": "#e60023"},
    {"name": "TikTok", "url": "https://www.tiktok.com/", "background": "#000"},
    {"name": "X", "url": "https://x.com", "background": "#000"},
    {"name": "Facebook","url": "https://www.facebook.com", "background": "#0866ff"},
    {"name": "Telegram", "url": "https://web.telegram.org/", "b2": "#2aa3dc"},
    {"name": "Airbnb", "url": "https://www.airbnb.com/", "background": "#ff5a5f"},
    {"name": "Booking", "url": "https://www.booking.com/", "background": "#003b95"}
  ],
  "Streaming" : [
    {"name": "Spotify", "url": "https://open.spotify.com/"},
    {"name": "Youtube", "url": "https://www.youtube.com/"},
    {"name": "YoutubeMusic", "url": "https://music.youtube.com/"},
    {"name": "DailyMotion", "url": "https://www.dailymotion.com/", "background": "#000"},
    {"name": "SoundCloud", "url": "https://soundcloud.com/", "icon": "./icons/app_soundcloud.svg", "background": "#ff5500"},
    "break",
    {"name": "Netflix", "url": "https://netflix.com/"},
    {"name": "Prime", "url": "https://www.primevideo.com/", "background": "#0578ff"},
    {"name": "HBO", "url": "https://www.hbomax.com/", "background": "#000"},
    {"name": "Disney+", "url": "https://www.disneyplus.com/"},
    {"name": "YTTV", "url": "https://tv.youtube.com/"},
    {"name": "Curiosity", "url": "https://curiositystream.com/"},
    {"name": "NBC", "url": "https://www.nbcuniversal.com/", "background": "#400371"},
    {"name": "NOS", "url": "https://nostv.pt/"},
    {"name": "Vodafone", "url": "https://tv.vodafone.pt/"},
    {"name": "MEO", "url": "https://meogo.meo.pt/"},
    ],
  "Office": [
    {"name": "Office365", "url": "https://www.office.com/" },
    {"name": "Outlook", "url": "https://outlook.live.com/mail/0/", "icon": "./icons/o365_outlook_2025.svg" },
    {"name": "Calendar", "url": "https://outlook.live.com/calendar/0/view/month"},
    {"name": "People", "url": "https://outlook.live.com/people/0/"},
    {"name": "Onedrive", "url": "https://onedrive.live.com/", "icon": "./icons/o365_onedrive_2025.svg" },    
    {"name": "Excel", "url": "https://excel.cloud.microsoft/"},
    {"name": "Word", "url": "https://www.office.com/launch/word?auth=1", "icon": "./icons/o365_word_2025.svg"},
    {"name": "PowerPoint", "url": "https://www.office.com/launch/powerpoint?auth=1", "icon": "./icons/o365_powerpoint_2025.svg"},
    {"name": "OneNote", "url": "https://www.onenote.com/notebooks?auth=1", "icon": "./icons/o365_onenote_2025.svg"},
    {"name": "Teams", "url": "https://teams.live.com/", "icon": "./icons/o365_teams_2025.svg"},
    {"name": "Sharepoint", "url": "https://sharepoint.live.com/", "icon": "./icons/o365_sharepoint_2025.svg"},
    {"name": "Forms", "url": "https://forms.office.com/"},
    {"name": "Designer", "url": "https://designer.microsoft.com/home"},

    "break",
    {"name": "Account", "url": "https://myaccount.google.com/u/0/"},
    {"name": "Keep", "url": "https://keep.google.com/"},
    {"name": "Find", "url": "https://www.google.com/android/find/", "icon": "./icons/google-find-my-device-2023.svg"},
    {"name": "GMail", "url": "https://mail.google.com/mail/u/0/#inbox", "icon": "./icons/google-gmail-2020.svg"},
    {"name": "Calendar", "url": "https://calendar.google.com/calendar/u/0/", "icon": "./icons/google-calendar-2020.svg"},
    {"name": "Contacts", "url": "https://contacts.google.com/u/0/", "icon": "./icons/google-contacts-2022.svg"},
    {"name": "Drive", "url": "https://drive.google.com/drive/my-drive", "icon": "./icons/google-drive-2020.svg"},
    {"name": "Photos", "url": "https://photos.google.com/u/0/", "icon": "./icons/google-photos-2020.svg"},
    {"name": "Maps", "url": "https://www.google.com/maps/u/0/", "icon": "./icons/google-maps-2020.svg"},
    {"name": "Books", "url": "https://books.google.com/u/0/", "icon": "./icons/google-play-books-2023.svg"},
    {"name": "Translate", "url": "https://translate.google.com", "icon": "./icons/google-translate-2016.svg"},
    {"name": "Docs", "url": "https://docs.google.com/document/u/0/", "icon": "./icons/google-docs-2020.svg"},
    {"name": "Sheets", "url": "https://docs.google.com/spreadsheets/u/0/", "icon": "./icons/google-sheets-2020.svg"},
    {"name": "Slides", "url": "https://docs.google.com/presentation/u/0/", "icon": "./icons/google-slides-2020.svg"},
    {"name": "Forms", "url": "https://docs.google.com/forms/u/0/", "icon": "./icons/google-forms-2020.svg"},
    {"name": "Play", "url": "https://play.google.com/store/apps"},
    {"name": "Meet", "url": "https://meet.google.com/u/0/","icon": "./icons/google-meet-2020.svg"},
    {"name": "Chat", "url": "https://chat.google.com/u/0/","icon": "./icons/google-chat-2023.svg"},
    {"name": "ShoppingList", "url": "https://shoppinglist.google.com/", "icon": "./icons/google-shopping-2020.svg"},
    ],
  "Dev": [
    {"name": "StackOverflow", "url": "https://stackoverflow.com/"},
    {"name": "MediaInfo","url": "https://mediaarea.net/MediaInfoOnline"},
    {"name": "VSCode", "url": "https://insiders.vscode.dev"},
    {"name": "Github", "url": "https://github.com"},
    {"name": "CodePen", "url": "https://codepen.io", "background": "#000"},
    {"name": "CodeSandbox", "url": "https://codesandbox.io", "icon": "./icons/code-sandbox.svg"},
    {"name": "ShaderToy", "url": "https://www.shadertoy.com", "icon": "./icons/shadertoy.png"},
    {"name": "ShaderFrog", "url": "https://shaderfrog.com/app/", "icon": "./icons/shaderfrog.png", "background": "#000"},
    {"name": "Codeit", "url": "https://codeit.codes/", "icon": "https://codeit.codes/icons/iphone-app-180.png", "background": "#000"},
    {"name": "Python", "url": "https://www.programiz.com/python-programming/online-compiler/", "icon": "./icons/lang-python.svg"},
    {"name": "Javascript", "url": "https://www.programiz.com/javascript/online-compiler/", "icon": "./icons/lang-js.svg", "background": "#f7df1e"},
    {"name": "Java", "url": "https://www.programiz.com/java-programming/online-compiler/", "icon": "./icons/lang-java.svg"},
    {"name": "C", "url": "https://www.programiz.com/c-programming/online-compiler/", "icon": "./icons/lang-c.svg"},
    {"name": "C++", "url": "https://www.programiz.com/cpp-programming/online-compiler/", "icon": "./icons/lang-cpp.svg"},
    {"name": "C#", "url": "https://www.programiz.com/csharp-programming/online-compiler/", "icon": "./icons/lang-csharp.svg"},
    {"name": "Bash", "url": "https://www.tutorialspoint.com/execute_bash_online.php", "icon": "./icons/lang-bash.svg"},
    "break",
    {"name": "Desmos", "url": "https://www.desmos.com/calculator"},
    {"name": "Overleaf", "url": "https://www.overleaf.com/"},
    {"name": "IT-Tools", "url": "https://it-tools.tech"},
    {"name": "CheatSheets", "url": "https://devhints.io/"},
    {"name": "imgColorPicker", "url": "https://imagecolorpicker.com"},
    {"name": "shapeShifter", "url": "https://shapeshifter.design/" },
    {"name": "WolframAlpha", "url": "https://www.wolframalpha.com/"},
  ]
}