const extra_data = {
    "diasgc": [
    { "url": "https://diasgc.github.io/arec-z/", "icon": "../arec-z/icon.svg", "name": "AudioRec"},
    { "url": "https://diasgc.github.io/tl2/", "icon": "../tl2/icon.svg", "name": "TimeLapse"},
    { "url": "https://diasgc.github.io/wwp/", "icon": "../wwp/icon.svg", "name": "Weather"},
    { "url": "https://diasgc.github.io/hexv/", "icon": "../hexv/icon.svg", "name": "HexView"},
    { "url": "https://diasgc.github.io/compass/", "icon": "../compass/icon.svg", "name": "Compass"},
    { "url": "https://diasgc.github.io/level/", "icon": "../level/icon.svg", "name": "Level"},
    { "url": "https://diasgc.github.io/glsl/", "icon": "../glsl/glsl.svg", "name": "GLSL"},
    { "url": "https://diasgc.github.io/glsl/editor.html", "icon": "../glsl/editor.svg", "name": "WebGl"},
    { "url": "https://diasgc.github.io/sensor/", "icon": "../sensor/icon.svg", "name": "Sensors"},
    { "url": "https://diasgc.github.io/ubuntu-setup/res/", "icon": "../ubuntu-setup/res/icon.svg", "name": "UbuntuWp"},
    { "url": "https://diasgc.github.io/ubuntu-setup/sw/", "icon": "../ubuntu-setup/sw/icon.svg", "name": "UbuntuSetup"},
    { "url": "https://diasgc.github.io/color/", "icon": "../color/icon.svg", "name": "Color"},
    ],
    "Shopping": [
    {"name": "Amazon", "url": "https://www.amazon.es/"},
    {"name": "eBay", "url": "https://www.ebay.es/"},
    {"name": "Temu", "url": "https://www.temu.com/" },
    {"name": "AliExpress", "url": "https://best.aliexpress.com/"},
    {"name": "KuantoKusta", "url": "https://www.kuantokusta.pt/"},
    {"name": "BackMarket", "url": "https://www.backmarket.pt/", "background": "#dbfb6c"},
    {"name": "Refurbed", "url": "https://www.refurbed.pt/", "background": "#332e80"},
    {"name": "OLX", "url": "https://www.olx.pt/", "background": "#23e5db"},
    {"name": "WeBuy/CeX", "url": "https://pt.webuy.com/", "background": "#fe0002"},
    "break",
    {"name": "PingoDoce", "url": "https://www.pingodoce.pt/?", "background": "#000"},
    {"name": "Continente", "url": "https://www.continente.pt/"},
    {"name": "Auchan", "url": "https://www.auchan.pt/"},
    {"name": "Lidl", "url": "https://www.lidl.pt/", "background": "#0050aa" },
    {"name": "Aldi", "url": "https://www.aldi.pt/"},
    {"name": "Intermarche", "url": "https://www.loja-online.intermarche.pt/"},
    "break",
    {"name": "Fnac", "url": "https://www.fnac.pt/"},
    {"name": "Worten", "url": "https://www.worten.pt/", "background": "#e41a15"},
    {"name": "Darty", "url": "https://darty.pt/", "background": "#ed1c27"},
    {"name": "RadioPopular", "url": "https://www.radiopopular.pt/"},
    {"name": "PCDiga", "url": "https://www.pcdiga.com/"},
    {"name": "GlobalData", "url": "https://www.globaldata.pt/"},
    {"name": "NovoAtalho", "url": "https://www.novoatalho.pt/"},
    {"name": "Mauser", "url": "https://mauser.pt", "background": "#ffd200"},
    {"name": "Castro", "url": "https://www.castroelectronica.pt/"},
    {"name": "Aquario", "url": "https://www.aquario.pt/"},
    "break",
    {"name": "Ikea", "url": "https://www.ikea.com/pt/pt/", "background": "#0050aa"},
    {"name": "Bricodepot", "url": "https://www.bricodepot.pt/"},
    {"name": "Leroy", "url": "https://www.leroymerlin.pt/"},
    {"name": "ZaraHome", "url": "https://www.zarahome.com/pt/"},
    {"name": "Shein", "url": "https://pt.shein.com/", "background": "black"},
    {"name": "Mango", "url": "https://shop.mango.com/"},
    {"name": "MaisGasolina", "url": "https://www.maisgasolina.com", "user": "1"},
    {"name": "PoupaPilim", "url": "https://poupapilim.com", "user": "1"},
    "break",
    {"name": "Google", "url": "https://store.google.com/"},
    {"name": "Apple", "url": "https://www.apple.com/"},
    {"name": "Oppo", "url": "https://www.oppo.com/"},
    {"name": "OnePlus", "url":"https://www.oneplus.com/", "background": "#f51220"},
    {"name": "Samsung", "url":"https://www.samsung.com/"},
    {"name": "Xiaomi", "url": "https://www.xiaomistore.pt/"},
    {"name": "Realme", "url": "https://www.realme.com/eu/", "background": "#ffc915"},
    {"name": "Chuwi", "url": "https://www.chuwi.com/pt/"  },
  ],
}